name: utils
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # DI
  kiwi: ^5.0.1
  # Networking
  http: ^1.2.2
  http_interceptor: ^2.0.0
  # State management
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  # Storages
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  # Routing
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
